// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerEntryType string

const (
	LedgerEntryTypeDebit  LedgerEntryType = "debit"
	LedgerEntryTypeCredit LedgerEntryType = "credit"
)

func (e *LedgerEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEntryType(s)
	case string:
		*e = LedgerEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEntryType: %T", src)
	}
	return nil
}

type NullLedgerEntryType struct {
	LedgerEntryType LedgerEntryType `json:"ledger_entry_type"`
	Valid           bool            `json:"valid"` // Valid is true if LedgerEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEntryType), nil
}

type TransactionStatusEnum string

const (
	TransactionStatusEnumPending   TransactionStatusEnum = "pending"
	TransactionStatusEnumCompleted TransactionStatusEnum = "completed"
	TransactionStatusEnumFailed    TransactionStatusEnum = "failed"
)

func (e *TransactionStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatusEnum(s)
	case string:
		*e = TransactionStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatusEnum: %T", src)
	}
	return nil
}

type NullTransactionStatusEnum struct {
	TransactionStatusEnum TransactionStatusEnum `json:"transaction_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if TransactionStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatusEnum), nil
}

type TransactionTypeEnum string

const (
	TransactionTypeEnumCredit   TransactionTypeEnum = "credit"
	TransactionTypeEnumDebit    TransactionTypeEnum = "debit"
	TransactionTypeEnumTransfer TransactionTypeEnum = "transfer"
)

func (e *TransactionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionTypeEnum(s)
	case string:
		*e = TransactionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionTypeEnum: %T", src)
	}
	return nil
}

type NullTransactionTypeEnum struct {
	TransactionTypeEnum TransactionTypeEnum `json:"transaction_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if TransactionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionTypeEnum), nil
}

type WalletTypeEnum string

const (
	WalletTypeEnumSavings WalletTypeEnum = "savings"
	WalletTypeEnumFixed   WalletTypeEnum = "fixed"
	WalletTypeEnumMisc    WalletTypeEnum = "misc"
)

func (e *WalletTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletTypeEnum(s)
	case string:
		*e = WalletTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletTypeEnum: %T", src)
	}
	return nil
}

type NullWalletTypeEnum struct {
	WalletTypeEnum WalletTypeEnum `json:"wallet_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if WalletTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WalletTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletTypeEnum), nil
}

type Ledger struct {
	ID            uuid.UUID          `json:"id"`
	WalletID      uuid.UUID          `json:"wallet_id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	EntryType     LedgerEntryType    `json:"entry_type"`
	Currency      string             `json:"currency"`
	BalanceBefore pgtype.Numeric     `json:"balance_before"`
	BalanceAfter  pgtype.Numeric     `json:"balance_after"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Otp struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Code      string             `json:"code"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      pgtype.Bool        `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID               uuid.UUID             `json:"id"`
	SenderWalletID   pgtype.UUID           `json:"sender_wallet_id"`
	ReceiverWalletID pgtype.UUID           `json:"receiver_wallet_id"`
	TransactionType  TransactionTypeEnum   `json:"transaction_type"`
	Amount           pgtype.Numeric        `json:"amount"`
	Description      pgtype.Text           `json:"description"`
	Status           TransactionStatusEnum `json:"status"`
	Currency         string                `json:"currency"`
	IdempotencyKey   string                `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz    `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	FullName     string             `json:"full_name"`
	PhoneNumber  string             `json:"phone_number"`
	Email        string             `json:"email"`
	Passwordhash string             `json:"passwordhash"`
	Username     string             `json:"username"`
	AccountNo    string             `json:"account_no"`
	Nationality  string             `json:"nationality"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID         uuid.UUID          `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Balance    pgtype.Numeric     `json:"balance"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	WalletType WalletTypeEnum     `json:"wallet_type"`
	Currency   string             `json:"currency"`
}
