// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otps (
    user_id,
    code,
    purpose,
    expires_at,
    used
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, user_id, code, purpose, expires_at, used, created_at
`

type CreateOTPParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Code      string             `json:"code"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      pgtype.Bool        `json:"used"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.UserID,
		arg.Code,
		arg.Purpose,
		arg.ExpiresAt,
		arg.Used,
	)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Purpose,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}
