// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (sender_wallet_id, receiver_wallet_id, transaction_type, amount, description, status, currency,idempotency_key) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, sender_wallet_id, receiver_wallet_id, transaction_type, amount, description, status, currency, idempotency_key, created_at, updated_at
`

type CreateTransactionParams struct {
	SenderWalletID   pgtype.UUID           `json:"sender_wallet_id"`
	ReceiverWalletID pgtype.UUID           `json:"receiver_wallet_id"`
	TransactionType  TransactionTypeEnum   `json:"transaction_type"`
	Amount           pgtype.Numeric        `json:"amount"`
	Description      pgtype.Text           `json:"description"`
	Status           TransactionStatusEnum `json:"status"`
	Currency         string                `json:"currency"`
	IdempotencyKey   string                `json:"idempotency_key"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.SenderWalletID,
		arg.ReceiverWalletID,
		arg.TransactionType,
		arg.Amount,
		arg.Description,
		arg.Status,
		arg.Currency,
		arg.IdempotencyKey,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderWalletID,
		&i.ReceiverWalletID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Currency,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingTransactionsByWalletId = `-- name: GetPendingTransactionsByWalletId :many
SELECT id, sender_wallet_id, receiver_wallet_id, transaction_type, amount, description, status, currency, idempotency_key, created_at, updated_at FROM transactions WHERE (sender_wallet_id = $1 OR recipient_wallet_id = $1) AND status = 'pending' ORDER BY created_at DESC
`

func (q *Queries) GetPendingTransactionsByWalletId(ctx context.Context, senderWalletID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getPendingTransactionsByWalletId, senderWalletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.SenderWalletID,
			&i.ReceiverWalletID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.Currency,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, sender_wallet_id, receiver_wallet_id, transaction_type, amount, description, status, currency, idempotency_key, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionById(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderWalletID,
		&i.ReceiverWalletID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Currency,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, sender_wallet_id, receiver_wallet_id, transaction_type, amount, description, status, currency, idempotency_key, created_at, updated_at FROM transactions WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderWalletID,
		&i.ReceiverWalletID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.Currency,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionsByWalletId = `-- name: GetTransactionsByWalletId :many
SELECT id, sender_wallet_id, receiver_wallet_id, transaction_type, amount, description, status, currency, idempotency_key, created_at, updated_at FROM transactions WHERE sender_wallet_id = $1 OR recipient_wallet_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetTransactionsByWalletIdParams struct {
	SenderWalletID pgtype.UUID `json:"sender_wallet_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) GetTransactionsByWalletId(ctx context.Context, arg GetTransactionsByWalletIdParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByWalletId, arg.SenderWalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.SenderWalletID,
			&i.ReceiverWalletID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.Currency,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions SET status = $1 WHERE id = $2
`

type UpdateTransactionStatusParams struct {
	Status TransactionStatusEnum `json:"status"`
	ID     uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.Status, arg.ID)
	return err
}
