// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    phone_number,
    email,
    passwordHash,
    username,
    account_no,
    nationality
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, full_name, phone_number, email, passwordhash, username, account_no, nationality, created_at, updated_at, country_code
`

type CreateUserParams struct {
	FullName     string `json:"full_name"`
	PhoneNumber  string `json:"phone_number"`
	Email        string `json:"email"`
	Passwordhash string `json:"passwordhash"`
	Username     string `json:"username"`
	AccountNo    string `json:"account_no"`
	Nationality  string `json:"nationality"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.Passwordhash,
		arg.Username,
		arg.AccountNo,
		arg.Nationality,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.Passwordhash,
		&i.Username,
		&i.AccountNo,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryCode,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, phone_number, email, passwordhash, username, account_no, nationality, created_at, updated_at, country_code FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.Passwordhash,
		&i.Username,
		&i.AccountNo,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryCode,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, phone_number, email, passwordhash, username, account_no, nationality, created_at, updated_at, country_code FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.Passwordhash,
		&i.Username,
		&i.AccountNo,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryCode,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, full_name, phone_number, email, passwordhash, username, account_no, nationality, created_at, updated_at, country_code FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.Passwordhash,
		&i.Username,
		&i.AccountNo,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryCode,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = COALESCE($1, full_name),
    phone_number = COALESCE($2, phone_number),
    email = COALESCE($3, email),
    passwordHash = COALESCE($4, passwordHash),
    username = COALESCE($5, username),
    account_no = COALESCE($6, account_no),
    nationality = COALESCE($7, nationality),
    updated_at = NOW()
WHERE id = $8
RETURNING id, full_name, phone_number, email, passwordhash, username, account_no, nationality, created_at, updated_at, country_code
`

type UpdateUserParams struct {
	FullName     pgtype.Text `json:"full_name"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Username     pgtype.Text `json:"username"`
	AccountNo    pgtype.Text `json:"account_no"`
	Nationality  pgtype.Text `json:"nationality"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.AccountNo,
		arg.Nationality,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.Passwordhash,
		&i.Username,
		&i.AccountNo,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CountryCode,
	)
	return i, err
}
