// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    user_id,
    wallet_type,
    currency
) VALUES ($1,$2,$3)
RETURNING id, user_id, balance, created_at, updated_at, wallet_type, currency
`

type CreateWalletParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	WalletType WalletTypeEnum `json:"wallet_type"`
	Currency   string         `json:"currency"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.WalletType, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WalletType,
		&i.Currency,
	)
	return i, err
}
